publish_to: none

name: attendance_manager
description: A modern attendance tracking app with smart features

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  pie_chart: ^5.1.0

  permission_handler: ^11.0.1

  shared_preferences: ^2.2.2

  # Core Packages
  provider: ^6.1.1
  intl: ^0.18.1
  path: ^1.8.3

  # Database & Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Notifications
  flutter_local_notifications: ^18.0.1
  android_alarm_manager_plus: ^4.0.7
  timezone: ^0.9.2

  # Background Processing
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: main
      path: workmanager

  # Sharing/Export
  share_plus: ^7.0.1

  # Date/Time Pickers
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

  remove_alpha_ios: true

flutter:
  uses-material-design: true


